### PR TITLE
pin to avoid pyvista 0.42.2

### PR DESCRIPTION
**Pull request by bjlittle**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bjlittle** [comment]
@conda-forge-admin, please rerender

**Comment by bjlittle** [comment]
@tkoyama010 Just noticed that `geovista` is experiencing issues with `pyvista` 0.42.2, so I'm going to temporarily pin back for the moment until I can investigate and diagnose.

**Comment by banesullivan** [comment]
> Just noticed that geovista is experiencing issues with pyvista 0.42.2

@bjlittle, not sure if you have already done this, but would you please report the specific issues you are having so that they can be addressed

**Comment by bjlittle** [comment]
@banesullivan Thanks for the nudge, but I've already captured this in https://github.com/bjlittle/geovista/issues/447 and @tkoyama010 kindly investigated to discover that the issue within `geovista` was due to the `pyvista` pull-request https://github.com/pyvista/pyvista/pull/4853, which was included in 0.42.2.

The issue arose in the `geovista` examples, which are not part of the CI, but we're now working to include image testing within `geovista` to give us automated coverage and avoid this situation again 👍 

See:
- https://github.com/bjlittle/geovista/pull/450
- https://github.com/conda-forge/staged-recipes/pull/24058

**Comment by banesullivan** [comment]
Thanks for the clarification! Forgive me for being a bit out of the loop

**Pull request merged**
